name: Sync Docs to docs-hub

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  sync:
    uses: DevOps-Course-2026/.github/.github/workflows/reusable-sync-docs.yml@main
    secrets: inherit
